In [5]:
import torch

In [6]:
print(torch.__version__)

2.11.0+cu128


In [7]:
if torch.cuda.is_available():
  print(f"GPU is available and using GPU is :{torch.cuda.get_device_name(0)}")
else:
  print("No bro using CPU:)")

GPU is available and using GPU is :Tesla T4


In [8]:
 torch.empty(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [9]:
torch.zeros(2,5)

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [10]:
torch.ones(1,2)

tensor([[1., 1.]])

In [11]:
torch.rand(2,3)

tensor([[0.0972, 0.9561, 0.5337],
        [0.7717, 0.3172, 0.3133]])

In [12]:
torch.rand(2,3)

tensor([[0.8669, 0.4944, 0.2204],
        [0.4306, 0.6059, 0.1242]])

In [13]:
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [14]:
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [15]:
x =torch.tensor([[1,2,3],[4,5,6]])
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [16]:
type(x)

torch.Tensor

In [17]:
torch.arange(0,24,2) #generates 24 evenly spaced values between 0 and 24 (inclusive)

tensor([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22])

In [18]:
torch.eye((4))

tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])

In [19]:
torch.full((3,3),24)

tensor([[24, 24, 24],
        [24, 24, 24],
        [24, 24, 24]])

In [20]:
x = torch.tensor([[1,2,3],[4,5,6]])
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [21]:
x.shape

torch.Size([2, 3])

In [22]:
torch.empty_like(x)

tensor([[132394088365456,       639674656,       639539488],
        [      639482352,               0,       605833424]])

In [23]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [24]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [25]:
torch.rand_like(x)

NotImplementedError: "check_uniform_bounds" not implemented for 'Long'

In [26]:
x.dtype

torch.int64

In [27]:
torch.tensor([2.,5.,7.], dtype = torch.int32)

tensor([2, 5, 7], dtype=torch.int32)

In [28]:
torch.tensor([2.,5.,7.], dtype = torch.float64)

tensor([2., 5., 7.], dtype=torch.float64)

In [29]:
x.to(torch.float32)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [30]:
torch.rand_like(x , dtype = torch.float32)

tensor([[0.2627, 0.0428, 0.2080],
        [0.1180, 0.1217, 0.7356]])

In [31]:
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [32]:
x+2

tensor([[3, 4, 5],
        [6, 7, 8]])

In [33]:
x-2

tensor([[-1,  0,  1],
        [ 2,  3,  4]])

In [34]:
x*2

tensor([[ 2,  4,  6],
        [ 8, 10, 12]])

In [35]:
x/3

tensor([[0.3333, 0.6667, 1.0000],
        [1.3333, 1.6667, 2.0000]])

In [36]:
x**2

tensor([[ 1,  4,  9],
        [16, 25, 36]])

In [37]:
a = torch.rand(3,2)
b = torch.rand(3,2)

In [38]:
a,b

(tensor([[0.7118, 0.7876],
         [0.4183, 0.9014],
         [0.9969, 0.7565]]),
 tensor([[0.2239, 0.3023],
         [0.1784, 0.8238],
         [0.5557, 0.9770]]))

In [39]:
a+b

tensor([[0.9357, 1.0899],
        [0.5967, 1.7253],
        [1.5526, 1.7335]])

In [40]:
a-b

tensor([[ 0.4879,  0.4852],
        [ 0.2399,  0.0776],
        [ 0.4411, -0.2205]])

In [41]:
a*b

tensor([[0.1594, 0.2381],
        [0.0746, 0.7426],
        [0.5540, 0.7391]])

In [42]:
a/b

tensor([[3.1790, 2.6049],
        [2.3445, 1.0942],
        [1.7938, 0.7743]])

In [43]:
a**b

tensor([[0.9267, 0.9303],
        [0.8560, 0.9180],
        [0.9983, 0.7614]])

In [44]:
c =  torch.tensor([1,-2,-3,4,5])

In [45]:
torch.abs(c)

tensor([1, 2, 3, 4, 5])

In [46]:
torch.neg(c)

tensor([-1,  2,  3, -4, -5])

In [47]:
d =  torch.tensor([1.1,2.5,3.4,4.9,5.6])

In [48]:
torch.round(d)

tensor([1., 2., 3., 5., 6.])

In [49]:
torch.ceil(d)

tensor([2., 3., 4., 5., 6.])

In [50]:
torch.floor(d)

tensor([1., 2., 3., 4., 5.])

In [51]:
torch.clamp(d, min = 3, max = 5)

tensor([3.0000, 3.0000, 3.4000, 4.9000, 5.0000])

In [52]:
e =  torch.randint(size=(2,3),low = 0 ,high = 44 , dtype = torch.float32)
e

tensor([[28., 31.,  1.],
        [17.,  6., 18.]])

In [53]:
torch.sum(e)

tensor(101.)

In [54]:
torch.sum(e, dim = 0)

tensor([45., 37., 19.])

In [55]:
torch.sum(e, dim = 1)

tensor([60., 41.])

In [56]:
torch.mean(e)

tensor(16.8333)

In [57]:
torch.mean(e, dim = 0)

tensor([22.5000, 18.5000,  9.5000])

In [58]:
torch.median(e)

tensor(17.)

In [59]:
torch.min(e)

tensor(1.)

In [60]:
torch.max(e)

tensor(31.)

In [61]:
torch.prod(e)

tensor(1593648.)

In [62]:
torch.std(e)

tensor(11.7884)

In [63]:
torch.var(e)

tensor(138.9667)

In [64]:
torch.argmax(e)

tensor(1)

In [65]:
torch.argmin(e)

tensor(2)

In [66]:
f = torch.randint(size = (2,3),low = 0, high =10)
g = torch.randint(size = (3,2),low = 0, high =10)

In [67]:
f,g

(tensor([[7, 0, 0],
         [9, 5, 7]]),
 tensor([[3, 9],
         [4, 0],
         [5, 7]]))

In [68]:
torch.matmul(f,g)

tensor([[ 21,  63],
        [ 82, 130]])

In [69]:
v1 = torch.tensor([1,2])
v2 = torch.tensor([3,4])
v1,v2

(tensor([1, 2]), tensor([3, 4]))

In [70]:
torch.dot(v1,v2)

tensor(11)

In [71]:
f


tensor([[7, 0, 0],
        [9, 5, 7]])

In [72]:
torch.transpose(f,0,1)

tensor([[7, 9],
        [0, 5],
        [0, 7]])

In [73]:
h = torch.randint(size = (3,3),low =0 ,high =10, dtype = torch.float32)

In [74]:
h

tensor([[5., 9., 9.],
        [7., 5., 9.],
        [8., 9., 7.]])

In [75]:
torch.det(h)

tensor(184.0000)

In [76]:
torch.inverse(h)

tensor([[-0.2500,  0.0978,  0.1957],
        [ 0.1250, -0.2011,  0.0978],
        [ 0.1250,  0.1467, -0.2065]])

In [77]:
k = torch.randint(size = (2,3) , low = 0 ,high = 10,dtype = torch.float32)

In [78]:
k

tensor([[9., 2., 6.],
        [7., 7., 8.]])

In [79]:
torch.log(k)

tensor([[2.1972, 0.6931, 1.7918],
        [1.9459, 1.9459, 2.0794]])

In [80]:
torch.sqrt(k)

tensor([[3.0000, 1.4142, 2.4495],
        [2.6458, 2.6458, 2.8284]])

In [81]:
torch.sigmoid(k)

tensor([[0.9999, 0.8808, 0.9975],
        [0.9991, 0.9991, 0.9997]])

In [82]:
torch.softmax(k, dim = 0)

tensor([[0.8808, 0.0067, 0.1192],
        [0.1192, 0.9933, 0.8808]])

In [83]:
torch.relu(k)

tensor([[9., 2., 6.],
        [7., 7., 8.]])

In [84]:
m = torch.rand(2,3)
n = torch.rand(2,3)
m,n

(tensor([[0.3687, 0.9053, 0.8356],
         [0.3039, 0.6726, 0.5740]]),
 tensor([[0.9233, 0.9178, 0.7590],
         [0.7775, 0.6179, 0.3379]]))

In [85]:
m.add_(n)

tensor([[1.2920, 1.8231, 1.5946],
        [1.0814, 1.2905, 0.9118]])

In [86]:
m

tensor([[1.2920, 1.8231, 1.5946],
        [1.0814, 1.2905, 0.9118]])

In [87]:
n

tensor([[0.9233, 0.9178, 0.7590],
        [0.7775, 0.6179, 0.3379]])

In [88]:
a

tensor([[0.7118, 0.7876],
        [0.4183, 0.9014],
        [0.9969, 0.7565]])

In [89]:
b = torch.clone(a)

In [90]:
id(a)

132388748166000

In [91]:
id(b)

132388748604704

In [92]:
a

tensor([[0.7118, 0.7876],
        [0.4183, 0.9014],
        [0.9969, 0.7565]])

In [93]:
b = a

In [94]:
id (a)

132388748166000

In [95]:
id(b)

132388748166000

In [96]:
torch.cuda.is_available()

True

In [97]:
device = torch.device("cuda")

In [98]:
device

device(type='cuda')

In [101]:
a =    torch.ones(4,4)

In [100]:
a

tensor([[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]])

In [102]:
a.reshape(2,2,2,2)

tensor([[[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]],


        [[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]]])

In [103]:
b = torch.rand(2,3)

In [104]:
b

tensor([[0.2170, 0.9454, 0.7116],
        [0.1157, 0.6574, 0.3451]])

In [105]:
a.flatten()

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [106]:
b

tensor([[0.2170, 0.9454, 0.7116],
        [0.1157, 0.6574, 0.3451]])

In [108]:
b.unsqueeze(0).shape

torch.Size([1, 2, 3])

In [109]:
b.unsqueeze(1).shape

torch.Size([2, 1, 3])

In [110]:
import numpy as np

In [112]:
a = torch.tensor([22,33,44])

In [113]:
type(a)

torch.Tensor

In [114]:
b = a.numpy()

In [115]:
type(b)

numpy.ndarray

In [116]:
b

array([22, 33, 44])

In [118]:
c = np.array([1,23,45])

In [119]:
c

array([ 1, 23, 45])

In [120]:
d = torch.from_numpy(c)

In [121]:
d

tensor([ 1, 23, 45])

In [122]:
type(d)

torch.Tensor

In [123]:
type(c)

numpy.ndarray